---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest_question(ingest_question)
	decompose_question(decompose_question)
	route_sources(route_sources)
	retrieve_chunks(retrieve_chunks)
	judge_grounding(judge_grounding)
	assess_confidence(assess_confidence)
	assemble_answer(assemble_answer)
	deliver_answer(deliver_answer)
	abstain(abstain)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest_question;
	assemble_answer --> deliver_answer;
	assess_confidence -.-> abstain;
	assess_confidence -. &nbsp;assemble&nbsp; .-> assemble_answer;
	decompose_question --> route_sources;
	deliver_answer -. &nbsp;end&nbsp; .-> __end__;
	deliver_answer -.-> abstain;
	ingest_question -. &nbsp;end&nbsp; .-> __end__;
	ingest_question -. &nbsp;decompose&nbsp; .-> decompose_question;
	judge_grounding -. &nbsp;assess&nbsp; .-> assess_confidence;
	judge_grounding -. &nbsp;retrieve&nbsp; .-> retrieve_chunks;
	retrieve_chunks --> judge_grounding;
	route_sources -. &nbsp;assess&nbsp; .-> assess_confidence;
	route_sources -. &nbsp;retrieve&nbsp; .-> retrieve_chunks;
	abstain --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
